#ifndef SMOLRTSP_LIMITS_H
#define SMOLRTSP_LIMITS_H

#ifndef SMOLRTSP_METHOD_SIZE
#define SMOLRTSP_METHOD_SIZE 16
#endif

#ifndef SMOLRTSP_REQUEST_URI_SIZE
#define SMOLRTSP_REQUEST_URI_SIZE 256
#endif

#ifndef SMOLRTSP_REASON_PHRASE_SIZE
#define SMOLRTSP_REASON_PHRASE_SIZE 128
#endif

#ifndef SMOLRTSP_MAX_RESPONSE_HEADERS
#define SMOLRTSP_MAX_RESPONSE_HEADERS 128
#endif

#ifndef SMOLRTSP_MAX_REQUEST_HEADERS
#define SMOLRTSP_MAX_REQUEST_HEADERS 128
#endif

#ifndef SMOLRTSP_MAX_VERSION_SIZE
#define SMOLRTSP_MAX_VERSION_SIZE 128
#endif

#ifndef SMOLRTSP_HEADERS_COUNT
#define SMOLRTSP_HEADERS_COUNT 64
#endif

#ifndef SMOLRTSP_HEADER_KEY_SIZE
#define SMOLRTSP_HEADER_KEY_SIZE 64
#endif

#ifndef SMOLRTSP_HEADER_VALUE_SIZE
#define SMOLRTSP_HEADER_VALUE_SIZE 512
#endif

#endif // SMOLRTSP_LIMITS_H
