/**
 * @file
 * @brief Implementation limits.
 */

#ifndef SMOLRTSP_LIMITS_H
#define SMOLRTSP_LIMITS_H

#define SMOLRTSP_METHOD_SIZE        16
#define SMOLRTSP_REQUEST_URI_SIZE   256
#define SMOLRTSP_RTSP_VERSION_SIZE  128
#define SMOLRTSP_REASON_PHRASE_SIZE 128
#define SMOLRTSP_HEADERS_COUNT      64
#define SMOLRTSP_HEADER_KEY_SIZE    64
#define SMOLRTSP_HEADER_VALUE_SIZE  512

#endif // SMOLRTSP_LIMITS_H
