#ifndef SMOLRTSP_LIMITS_H
#define SMOLRTSP_LIMITS_H

#ifndef SMOLRTSP_METHOD_SIZE
#define SMOLRTSP_METHOD_SIZE 16
#endif

#ifndef SMOLRTSP_REQUEST_URI_SIZE
#define SMOLRTSP_REQUEST_URI_SIZE 256
#endif

#ifndef SMOLRTSP_REASON_PHRASE_SIZE
#define SMOLRTSP_REASON_PHRASE_SIZE 128
#endif

#endif // SMOLRTSP_LIMITS_H
